package com.bucur.exceptions.error_vs_exception;

public class DemoError {

    public static void main(String[] args) {
        StackOverflow.work(5);
    }
}
